### ISSUE TITLE
neptune mlflow integration issue with artifact_path

### ISSUE THREAD

**Issue by wpalmerta** [neptune-ai/neptune-mlflow#29]
I'm using
neptune-client 0.10.7
neptune-mlflow 0.2.5
mlflow 1.19.0

and get an issue when running
neptune mlflow

that suggests it is having issues with the location of the artifacts

Traceback (most recent call last):
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\wpalmer\Anaconda3\envs\TARecommender\Scripts\neptune.exe\__main__.py", line 7, in <module>
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\neptune_mlflow_plugin\__init__.py", line 39, in sync
    return run_sync(path=path, project=project)
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\neptune_mlflow\sync.py", line 45, in sync
    loader.run()
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\neptune_mlflow\data_loader.py", line 52, in run
    exp_uuid = self._create_neptune_experiment(experiment, run)
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\neptune_mlflow\data_loader.py", line 73, in _create_neptune_experiment
    with path_utils.Path(artifacts_path):
  File "c:\users\wpalmer\anaconda3\envs\tarecommender\lib\site-packages\path\__init__.py", line 193, in __enter__
    os.chdir(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: Path('//C:/Users/wpalmer/Projects/TARecommender/mlruns/0/65c802ae45fe473699ef67da01eaa1a2/artifacts')

The run information like params and metrics for the run sync just not anything in the artifacts folder (the error also occurs if the artifacts folder is empty)

**Comment by Raalsky** [comment]
Hey @wpalmerta,
Thank you for your report. Check latest `neptune-mlflow` package version `0.2.6`. https://pypi.org/project/neptune-mlflow/ it includes a fix for Windows paths.
