### ISSUE TITLE
Getting `bravado.exception.HTTPUnprocessableEntity: 422` when trying to sync MLflow to Neptune

### ISSUE THREAD

**Issue by AlxndrMlk** [neptune-ai/neptune-mlflow#31]
Hi,

I am trying to synchronize my local MLflow experiemnts with Neptune. 

I use `neptune mlflow --project ...` to do so. 

Everything worked fine so far and I was able to perform synchronization, but this time I am getting an exception (full traceback below).

The only thing that comes to my mind that has changed between the successful synchronization trials before and now is that I deleted a couple of experiment runs in my local MLflow UI in the meanwhile. These runs were a part of an experiment that I synchronized successfully before and cannot synchronize now.

Any ideas on how to solve it?

Thanks,
Alex

```python
Loading run Exp 01/384e83a7b2f340498086d22b8cdc31e7
Traceback (most recent call last):
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\Scripts\neptune.exe\__main__.py", line 7, in <module>
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\neptune_mlflow_plugin\__init__.py", line 39, in sync
    return run_sync(path=path, project=project)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\neptune_mlflow\sync.py", line 45, in sync
    loader.run()
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\neptune_mlflow\data_loader.py", line 54, in run
    exp_uuid = self._create_neptune_experiment(experiment, run)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\neptune_mlflow\data_loader.py", line 71, in _create_neptune_experiment
    handle_uncaught_exceptions=True
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\neptune\projects.py", line 462, in create_experiment
    checkpoint_id=checkpoint_id,
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\neptune\utils.py", line 298, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\neptune\internal\api_clients\hosted_api_clients\hosted_alpha_leaderboard_api_client.py", line 317, in create_experiment
    operations=init_experiment_operations,
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\neptune\utils.py", line 298, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\neptune\internal\api_clients\hosted_api_clients\hosted_alpha_leaderboard_api_client.py", line 973, in _execute_operations
    self.leaderboard_swagger_client.api.executeOperations(**kwargs)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\bravado\http_future.py", line 200, in response
    swagger_result = self._get_swagger_result(incoming_response)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\bravado\http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\bravado\http_future.py", line 303, in _get_swagger_result
    self.request_config.response_callbacks,
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\bravado\http_future.py", line 353, in unmarshal_response
    raise_on_expected(incoming_response)
  File "C:\Users\aleks\anaconda3\envs\tf-graphs-probability\lib\site-packages\bravado\http_future.py", line 422, in raise_on_expected
    swagger_result=http_response.swagger_result)
bravado.exception.HTTPUnprocessableEntity: 422
```

**Comment by Blaizzy** [comment]
Hi @AlxndrMlk 

Prince here, a Data Scientist at Neptune.ai

Let me see if I understood your query properly,

You created runs in the past and synced them successfully to Neptune and more recently you created new runs and deleted the data from MLflow and then you tried to sync metadata to Neptune.

If this is the case I believe you have to delete .neptune folder and re-create the experiments and the sync them to Neptune.

Please let me if this helps you! 

Cheers,
Prince
